# Documentation for ACL policy: https://aka.ms/gim/docs/policy/acl

name: Access control list
description: List of teams and their permission levels
resource: repository
where:
configuration:
  manageAccess:
    - member: sleonard
      role: Maintain
    - member: shawnadrockleonard
      role: Maintain
    - member: shnagpur_microsoft
      role: Maintain
    - member: vsaroopchand
      role: Maintain
    - member: maddierosenelson
      role: Write
    - member: ercenk
      role: Write